/**
 * @module constants
 * @author Charles Blais, Natural Resources Canada <charles.blais@canada.ca>
 */

export const COUNTRY_CODES = {
    aq: 'Antarctica',
    ar: 'Argentina',
    at: 'Austria',
    au: 'Australia',
    be: 'Belgium',
    bg: 'Bulgaria',
    br: 'Brazil',
    ca: 'Canada',
    cf: 'Central African Republic',
    cl: 'Chile',
    cn: 'China',
    cz: 'Czech Republic',
    de: 'Germany',
    dk: 'Denmark',
    dz: 'Algeria',
    es: 'Spain',
    et: 'Ethiopia',
    fi: 'Finland',
    fk: 'Falkland Islands (Islas Malvinas)',
    fr: 'France',
    gb: 'United Kingdom',
    gf: 'French Guiana',
    gl: 'Greenland',
    gr: 'Greece',
    gs: 'South Georgia and the South Sandwich Islands',
    hr: 'Croatia',
    hu: 'Hungary',
    ie: 'Republic of Ireland',
    in: 'India',
    it: 'Italy',
    jp: 'Japan',
    kr: 'Korea',
    kz: 'Kazakhstan',
    lb: 'Lebanon',
    mg: 'Madagascar',
    mv: 'Maldives',
    mx: 'Mexico',
    na: 'Namibia',
    no: 'Norway',
    nz: 'New Zealand',
    pe: 'Peru',
    pf: 'French Polynesia',
    pk: 'Pakistan',
    pl: 'Poland',
    ro: 'Romania',
    rs: 'Republic of Serbia',
    ru: 'Russia',
    se: 'Sweden',
    sh: 'Saint Helena, Ascension and Tristan da Cunha, British Overseas Territories',
    sk: 'Slovakia',
    sn: 'Senegal',
    tf: 'French Southern and Antarctic Lands',
    tr: 'Turkey',
    tw: 'Taiwan',
    ua: 'Ukraine',
    us: 'United States of America',
    vn: 'Vietnam',
    ws: 'Western Samoa',
    za: 'South Africa',
  };
